package net.arin.phonescreen.doNotModify.equality;

public class SomeBean {
   String propertyA;
   Integer propertyB;

   public String getPropertyA() {
      return propertyA;
   }

   public void setPropertyA(String propertyA) {
      this.propertyA = propertyA;
   }

   public Integer getPropertyB() {
      return propertyB;
   }

   public void setPropertyB(Integer propertyB) {
      this.propertyB = propertyB;
   }

   /*
    * Don't think to much about this. It was generated by IntelliJ. Trust that it behaves as you would
    * expect. Two SomeBeans are equal() if their fields are equal()
    */
   @Override
   public boolean equals(Object o) {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;

      SomeBean someBean = (SomeBean) o;

      if (propertyA != null ? !propertyA.equals(someBean.propertyA) : someBean.propertyA != null) return false;
      if (propertyB != null ? !propertyB.equals(someBean.propertyB) : someBean.propertyB != null) return false;

      return true;
   }

   @Override
   public int hashCode() {
      int result = propertyA != null ? propertyA.hashCode() : 0;
      result = 31 * result + (propertyB != null ? propertyB.hashCode() : 0);
      return result;
   }
}
